name: GmR
version: '${project.version}'
main: me.fr3ckzdk.asiii.gmrjava.GmrJava
api-version: 1.8
authors: [ Fr3ckz, Asiii ]
description: GmR Officielt plugin, lavet til SA
commands:
  gmr:
    description: GmR kommando